name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is 'Greeting'. Something!
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: nohomers/no-homers-hello-world-docker-action@11767_output_case_test
        with:
          who-to-greet: 'Lisa Simpson'
        id: hello
      - name: Number of homers allowed
        run: echo "The number of homers allowed is {{ steps.hello.outputs.homers-allowed }}."
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
